FUSETOOLS2-611 - fixing flaky tests
jboss-fuse/vscode-atlasmap pull request #429
Opened 2020-09-09 13:27 UTC by lhein

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

2020-09-09 14:26 UTC, apupier requested changes

2020-09-09 14:26 UTC, apupier commented on src/test/command.start.test.ts
> +		atlasMapWebView.default?.currentPanel?._panel?.webview?.html,
the failign assertion is ignored. you can notice it by changing the expectedAtlasmapTitle to somethign that it no t part of the page. The tests are still passing

2020-09-09 14:46 UTC, lhein commented on src/test/command.start.test.ts
> +		atlasMapWebView.default?.currentPanel?._panel?.webview?.html,
Did u test that? When I change `expectedAtlasMapTitle` to something else the tests fail just fine for me.

2020-09-09 14:57 UTC, apupier commented on src/test/command.start.test.ts
> +		atlasMapWebView.default?.currentPanel?._panel?.webview?.html,
:'-( code is not compiled automatically

it is failing for me too

2020-09-09 17:12 UTC, bfitzpat approved these changes
definitely more straightforward

2020-09-09 20:28 UTC, djelinek approved these changes
👍

2020-09-10 06:45 UTC, apupier approved these changes

2020-09-10 10:44 UTC, merged