fix: Provide Atlasmap getting started guide in README.md
jboss-fuse/vscode-atlasmap pull request #510
Opened 2021-01-14 07:18 UTC by jpav

Fixes #509

2021-01-14 12:00 UTC, apupier requested changes
- please put the jira issue number in commit message

2021-01-14 12:00 UTC, apupier commented on README.md
> +### Getting started
I think the "getting started" is a bit misleading in the context of the readme of VS Code AtlasMap.

To get started, it is more the "Open AtlasMap" command that seems important. And then pointing to the AtlasMap documentation to have more information on using the AtlasMap UI.

2021-01-14 12:10 UTC, lhein commented on README.md
> +    on the file system. Also, the option to export to a catalog is now under the `AtlasMap` menu rather that via a toolbar
Rather than instead of rather that....looks fine to me

2021-01-14 14:59 UTC, jpav commented on README.md
> +### Getting started
I assume you mean in the original #509 issue? If so, yes, will do.

2021-01-14 15:00 UTC, jpav commented on README.md
> +-   The look & feel of AtlasMap has changeed since the documentation was last updated and some of its screenshots have not yet been
I assume you mean in the original #509 issue? If so, will do.

2021-01-14 15:24 UTC, jpav commented on README.md
> +### Getting started
I actually realized I put this all under the Features heading. I will move things around and change Getting Starting to Using AtlasMap.

2021-01-15 08:38 UTC, apupier requested changes
a last small change suggestion.

Globally, it is greatly improving the readme.

2021-01-15 08:38 UTC, apupier commented on README.md
> +-   Java 8+ must be installed on system path
I think the prerequisites should be either at the top or at the bottom but it feels a bit strange in the middle

2021-01-15 08:40 UTC, apupier commented on README.md
> +-   The look & feel of AtlasMap has changeed since the documentation was last updated and some of its screenshots have not yet been
Not sure what is the most relevant to not forget it withotu bothering end users.
Maybe in the issue, it is enough.

2021-01-15 08:41 UTC, apupier commented on README.md
> +-   The look & feel of AtlasMap has changeed since the documentation was last updated and some of its screenshots have not yet been
or maybe creating an issue mentioning to update the readme linked to the documentation update issue is even better. it will allow to have an opened issue in our project so easier to notice.

2021-01-15 09:16 UTC, jpav commented on README.md
> +-   Java 8+ must be installed on system path
Will do

2021-01-15 09:33 UTC, apupier requested changes
please put the jira issue number in commit message

2021-01-15 09:34 UTC, jpav commented
Okay. I have no idea why this build is failing now.

2021-01-15 09:40 UTC, apupier commented
> I have no idea why this build is failing now.

me neither. it is very strange. the only difference that i spotted is a different circleci/node image version
https://app.circleci.com/pipelines/github/jboss-fuse/vscode-atlasmap/107/workflows/810f3d50-8ac9-4b7c-9a23-a5b1936d4095/jobs/121/parallel-runs/0/steps/0-0 9e422f7ff21351b5a6d257cf666b4947b905384907b331de6d3ed0bb0496b085

https://app.circleci.com/pipelines/github/jboss-fuse/vscode-atlasmap/109/workflows/96ace805-a4c7-4227-b461-a617ee13ae07/jobs/124/parallel-runs/0/steps/0-0 1a817546b1072e7cdcdeaaea5db3448c06b5eafa0d4318f18ed97c7b66730f95

There is same OS Ubuntu 18.04.04, same VS Code 1.52.2

2021-01-15 09:41 UTC, merged

2021-01-15 09:48 UTC, apupier commented
merged too fast, the PR wasn't approved.
you put the github issue number, not the jira issue number. When using the github issue, better to use #xxx notation to have automatic link. but too late to fix this time as it is merged

2021-01-15 09:51 UTC, jpav commented
Oh, sorry, I didn't know what the procedure was. In Atlasmap project, merge ability is only enabled after approval, so I assumed it was okay once I addressed all concerns. Regarding the issue number, there isn't a direct JIRA issue this addresses other than the epic itself, which contains many other issues. I think I can still update the PR though; I'll try.

2021-01-15 09:53 UTC, apupier commented
as it is for the commit message, it is already on the master. We do not force push on the master, this is too risky.

2021-01-15 09:54 UTC, jpav commented
k, I'll make sure not to commit prematurely in the future too.