FUSETOOLS2-1372 - adding a command to create and open an adm file
jboss-fuse/vscode-atlasmap pull request #729
Opened 2021-11-18 13:08 UTC by lhein

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

2021-11-18 13:24 UTC, apupier requested changes
- in case of already existing files, the file is overwritten
- need a test
- either in this PR or in another one but need to add the telemetry

2021-11-18 13:24 UTC, apupier commented on package.json
> +			"title": "Create AtlapMap file",
```suggestion
			"title": "Create AtlasMap file",
```

2021-11-18 13:24 UTC, apupier commented on src/extension.ts
> +			});
using the wait notation everywhere will bemore readable, somethign like:
```suggestion

		const fileName = await vscode.window.showInputBox( {placeHolder: "Enter the name of the new AtlasMap file"});
		var file: string = `${selectedWorkspaceFolder.uri.fsPath}/${fileName}`;
		if (!file.toLowerCase().endsWith('.adm')) {
			file += '.adm';
		}
		await vscode.workspace.fs.writeFile(vscode.Uri.file(file), Buffer.from(''));
		await vscode.commands.executeCommand('vscode.open', vscode.Uri.file(file));

```

2021-11-18 13:24 UTC, lhein commented
First iteration adding only a global command. In the next step it might be handy to have it also in the context menu of the file explorer in VS Code.

2021-11-18 13:49 UTC, lhein commented
implemented the suggested fixes and added a file exists check as well as the telemetry event and added the change to the changeLog....test is still missing

2021-11-24 14:13 UTC, apupier requested changes
I think the functionality worth a note in the readme

2021-11-24 14:13 UTC, apupier commented on src/extension.ts
> +	sendCreateEvent();
I think it is better to send the create event at the end of the function for these reasons:
- in case of failure, the main functionality is not completely broken
- in case it is taking a non negligeable time, it is not slowing down the main functionality
- it allows to send the element only when the command is really called successfully (avoids sending event when users are selecting the command but not going to the end of it)

2021-11-24 14:13 UTC, apupier commented on src/extension.ts
> +		}
can use a simpler method fs.existsSync  https://github.com/camel-tooling/vscode-camelk/blob/ed9c4e66feebb48d7a0c4f06087e321752288850/src/commands/NewIntegrationFileCommand.ts#L101

2021-11-24 14:13 UTC, apupier commented on src/extension.ts
> +		await vscode.workspace.fs.writeFile(vscode.Uri.file(file), Buffer.from(''));
using a validator on the filed allows to have a faster feedback to users. For instance https://github.com/camel-tooling/vscode-camelk/blob/ed9c4e66feebb48d7a0c4f06087e321752288850/src/commands/NewIntegrationFileCommand.ts#L62

2021-11-24 14:13 UTC, apupier commented on src/extension.ts
> +		const fileName: string = await vscode.window.showInputBox( {placeHolder: "Enter the name of the new AtlasMap file"});
could be ncie to validate also that it doesn't contain invalid character for filename, see for example https://github.com/camel-tooling/vscode-camelk/blob/ed9c4e66feebb48d7a0c4f06087e321752288850/src/commands/NewIntegrationFileCommand.ts#L104

2021-11-24 14:13 UTC, apupier commented on src/test/commands/atlasmap.file.create.test.ts
> +	let testADMFileName: string = 'test.adm';
```suggestion
	const testADMFileName: string = 'test.adm';
```

2021-11-24 14:13 UTC, apupier commented on src/test/commands/atlasmap.file.create.test.ts
> +	let dummyADMFileName: string = 'dummy.adm';
```suggestion
	const dummyADMFileName: string = 'dummy.adm';
```

2021-11-24 14:20 UTC, lhein commented on src/extension.ts
> +	sendCreateEvent();
yep, good point

2021-11-24 14:21 UTC, lhein commented on src/extension.ts
> +		}
I did not want to use that library but rather use the vscode internal fs api which does not have this function.

2021-11-24 14:29 UTC, apupier commented on src/extension.ts
> +			// file doesn't exist - that's good
the error type needs to be checked. Otherwise, it can be a completely another error thrown.

2021-11-24 14:30 UTC, apupier commented on src/extension.ts
> +			if (stat && stat.type === vscode.FileType.File) {
why checking for type of file? If it is a folder which exists with the name, we also need to detect it as an error

2021-11-24 14:32 UTC, apupier commented on src/extension.ts
> +		}
it introduces more code but well why not. needs to handle these 2 comments then: https://github.com/jboss-fuse/vscode-atlasmap/pull/729/files#r756130524 and https://github.com/jboss-fuse/vscode-atlasmap/pull/729/files#r756131135

2021-11-24 14:36 UTC, apupier commented on src/extension.ts
> +		}
in the VS Code samples, to check the existence they are using https://github.com/microsoft/vscode-extension-samples/blob/0b3a31bf2bdd388ac4fdc0ccea2fb1315abfe3e3/fsconsumer-sample/src/extension.ts#L27-L31

so means not checking for error type. So I guess that implicitly they defined that there is a single error possible

2021-11-24 14:38 UTC, apupier commented on src/extension.ts
> +			// file doesn't exist - that's good
this is not done in official example...
https://github.com/microsoft/vscode-extension-samples/blob/0b3a31bf2bdd388ac4fdc0ccea2fb1315abfe3e3/fsconsumer-sample/src/extension.ts#L30

2021-11-24 14:45 UTC, apupier commented on src/extension.ts
> +		} catch (error) {
`error` variable can be removed as it is not used after

2021-11-24 14:49 UTC, lhein commented on src/extension.ts
> +		await vscode.workspace.fs.writeFile(vscode.Uri.file(file), Buffer.from(''));
that is a good improvement

2021-11-24 15:24 UTC, lhein commented on src/extension.ts
> +		const fileName: string = await vscode.window.showInputBox( {placeHolder: "Enter the name of the new AtlasMap file"});
good idea!

2021-11-24 15:30 UTC, apupier commented on package-lock.json
> +	"lockfileVersion": 1,
seems you are using an older version of npm locally.
You will need to revert the package-lock.json and the change of dependency in package;json.
Upgrade npm
call again the npm install valid-filename@3.1.0

2021-11-24 15:57 UTC, apupier commented on src/extension.ts
> +		sendCreateEvent();
note: Having it in the finally means the event is sent even when a user finally escape from the command and doesn't go to the end.

2021-11-24 15:59 UTC, lhein commented on src/extension.ts
> +		sendCreateEvent();
yep, but he invoked the command. Don't we want to track that? Do we really want to track only successful invocations?

2021-11-24 16:05 UTC, lhein commented on package-lock.json
> +	"lockfileVersion": 1,
reverted to v2

2021-11-24 16:05 UTC, apupier commented on src/extension.ts
> +		sendCreateEvent();
in an ideal word, tracking each cases would be nice, with the step where the user abandoned or if there was an exception that prevented the command to go to the end.

As a first iteration, both (track all or only successful) are fine. Both are their advantages an drawbacks. In other Camel Tooling extensions, we went for the other case, to send for only successful ones.
(and another iteration might not be worthy until we have thousands of users)

2021-11-24 16:10 UTC, lhein commented on src/extension.ts
> +		sendCreateEvent();
ok, only tracking the successful calls now to align with the other extensions.

2021-11-24 16:23 UTC, lhein commented
![createAndOpenADM](https://user-images.githubusercontent.com/435853/143276408-1a2f1818-b9d8-411f-a2f4-a65be0412d8d.gif)

2021-11-25 08:35 UTC, apupier requested changes
remains the package-lock.json, see https://github.com/jboss-fuse/vscode-atlasmap/pull/736 to see the benefit on the diff with the steps I mentioned to update the dependencies
- revert package-lock.json to state before adding it
- remove valid-filename from package.json
- update local npm to version 7+ (for instance using nvm with command
nvm use lts/gallium)
- call nvm install valid-filename@3.1.0

The best will be to do it on this branch and to squash the commit that modifies the package.json

2021-11-25 10:02 UTC, apupier approved these changes

2021-11-25 10:02 UTC, merged