[FUSETOOLS2-1644] Updated developers info.
jboss-fuse/vscode-atlasmap pull request #831
Opened 2022-06-15 21:24 UTC by joshiraez

Left Lars as a contributtor this time as he still contributed to the codebase and it made sense

But if it was a mistake feel free to comment/edit :)

2022-06-16 07:44 UTC, apupier requested changes

2022-06-16 07:44 UTC, apupier commented on package.json
> +			"url": "http://redhat.com"
I noticed that above it is not done but it is better to use https url everywhere, it avoids potential security issues

2022-06-16 09:42 UTC, joshiraez commented on package.json
> +			"url": "http://redhat.com"
Fixed

2022-06-21 07:42 UTC, apupier commented
Can you rebase please? The issue on Mac should have been fixed

2022-06-21 16:26 UTC, joshiraez commented
I think the MacOS tests are still broken. I canceled the job because it had been running for 50m and there was an error "Unable to retrieve AtlasMap frame" over and over.

2022-06-22 08:41 UTC, apupier approved these changes

2022-06-22 09:14 UTC, merged