FUSETOOLS2-1737 - Allow choice of placement of .adm file
jboss-fuse/vscode-atlasmap pull request #879
Opened 2022-09-06 16:17 UTC by joshiraez

Related issue: https://issues.redhat.com/browse/FUSETOOLS2-1737

Provides a choice to select a directory inside the workspace for the adm file.

![admChooseDirectory](https://user-images.githubusercontent.com/17336236/188685669-f8a53e40-0700-4ee8-8b66-6ef669c84256.gif)

2022-09-07 07:56 UTC, apupier requested changes
- when clicking cancel in the window to choose a folder, it gives an error dialog after
![errorOnCancel](https://user-images.githubusercontent.com/1105127/188817786-4f75412b-e093-43e7-910b-b22b654d15ad.gif)
- please add a test for the new use cases
- need to update the changelog

2022-09-07 07:56 UTC, apupier commented on src/extension.ts
> +			["Same as workspace", "Select a folder inside workspace"], {placeHolder: "Select the location of the .adm file"}
Instead of "Same as workspace", i think "workspace root" or "root folder of the workspace" would be clearer

2022-09-07 07:56 UTC, apupier commented on src/extension.ts
> +				const admFolderUri = (await vscode.window.showOpenDialog(options))[0];
admFolderUri is redeclared in this scope and not used.
In consequence, if we choose a folder outside of workspace folder one time, it will always fail as it will keep this one.

2022-09-07 07:56 UTC, apupier commented on src/extension.ts
> +			};
better to give a title to the window dialog

Especially useful when the dialog is opening in the background (what is the ready?):

![image](https://user-images.githubusercontent.com/1105127/188818344-dbe95ba8-8aa7-413d-b156-fa6c579e0c73.png)

2022-09-07 07:56 UTC, apupier commented on src/extension.ts
> +				vscode.window.showErrorMessage("Select a folder inside the workspace.")
the message is barely visible in the background of the file picker, not at all if the folder dialog is open in max size.

2022-09-07 07:56 UTC, apupier commented on src/extension.ts
> +			vscode.window.showInformationMessage(file);
Displaying the path of the file only is not user-friendly. Either remove this message and stay like before or need to rpovide a better message explaining what this path is. Sounds the first solution is easier

2022-09-07 07:56 UTC, apupier commented on src/extension.ts
> +				vscode.window.showErrorMessage("Select a folder inside the workspace.")
i think the message cna be more informative. Something ike:
"The chosen folder was outside of the workspace. You need to select a folder inside the workspace to create the AtlasMap Data transformation file."

2022-09-07 11:12 UTC, joshiraez commented on src/extension.ts
> +				const admFolderUri = (await vscode.window.showOpenDialog(options))[0];
Wops, and the const inside gets out of scope and is deleted. You are right

2022-09-14 16:51 UTC, joshiraez commented
Ok so there is one happy test path and a few fixes and functionalities.

Things left to be done are:
* Check if there is some Api for an error popup instead of a notification
* See how to move a lot of the strings to package.json instead of having them happily around (specially because we evaluate against those values)
* Creating 2 tests for the unhappy paths

I'll try to at least create the 2 tests later today and start checking how to migrate to the json. I'll ask for the review after that.

Current state is:
![AtlasMapAdmLocationChooser2](https://user-images.githubusercontent.com/17336236/190215000-e118e34b-bce9-4fa7-9549-dcb88cf2c345.gif)

I'll be updating the first post with this picture as well

2022-09-14 16:51 UTC, joshiraez commented
I forgot the changelog. Doing it now too

2022-09-14 17:02 UTC, joshiraez commented
Somehow I broke all the tests while creating/refactoring the ones for .adm file :( I'll have to check up tomorrow

2022-09-15 08:29 UTC, joshiraez commented
So there is this for the popups https://code.visualstudio.com/api/references/vscode-api#CancellationError but I really don't like it for either the cancellation, or when the user choooses a folder outside the workspace. So i'll be leaving that be.

I'm looking for what is the preferred method to store application strings now. If there is none, I'll leave them be as they are quite localized now in their own functions

2022-09-15 09:10 UTC, joshiraez commented
New peek gif with the latest code changes
![AtlasMapAdmLocationChooser3](https://user-images.githubusercontent.com/17336236/190364478-9b14b84e-51a7-4813-b7ca-bff590b253f6.gif)

2022-09-15 11:14 UTC, apupier requested changes
- when hitting escape on step to select workspace root or select inside a folder, the wizard is continuing like "Workspace root" was selected
![escapeIgnored](https://user-images.githubusercontent.com/1105127/190389422-b30c2dd8-6643-43cb-bfa5-843bacc78c98.gif)
- Given that we go from a single method of 10 lines to multiple methods taking 100+ lines, it might be worthy to extract it in a specific file

2022-09-15 12:11 UTC, joshiraez commented
On it now

2022-09-15 16:06 UTC, joshiraez commented
Should be ok now

2022-09-16 13:24 UTC, apupier approved these changes
useful feature added :clap:

2022-09-16 13:30 UTC, merged